name: ENZO SEGOVIA
favicon: null
layout_spectrum: 0.9447708835359663
typography_spectrum: 0.11078
title: ' '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151314'
    - '#383639'
    - '#d2d5ce'
    - '#ada28e'
    - '#7f8c92'
  brandStrength: 0.8236109802965075
  lightness: 0.7567537298891693
  saturation: 0.3278421685099602
  rhythmicContrast: 0.75
purpose: []
