name: ENZO SEGOVIA
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5031
title: ' '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030207'
    - '#c6d5e8'
    - '#809086'
    - '#007c8f'
    - '#b42223'
  brandStrength: 0.1875
  lightness: 0.7567537298891693
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
